export default [
    "dowolnie",
    "Albania",
    "Armenia",
    "Australia",
    "Austria", 
    "Azerbejdżan", 
    "Bali",
    "Bośnia i Hercegowina",
    "Bułgaria",
    "Chiny", 
    "Chorwacja",
    "Cypr",
    "Czarnogóra", 
    "Czechy",
    "Dania",
    "Dominikana",
    "Egipt", 
    "Ekwador",
    "Etiopia",
    "Francja",
    "Grecja",
    "Gwadelupa",
    "Hiszpania", 
    "Holandia",
    "Indie", 
    "Indonezja",
    "Irlandia", 
    "Islandia",
    "Izrael",
    "Kambodża",
    "Kanada",
    "Kostaryka", 
    "Kuba",
    "Liechtenstein",
    "Luksemburg",
    "Madagaskar",
    "Malediwy", 
    "Malezja",
    "Malta",
    "Maroko", 
    "Martynika",
    "Mauritius", 
    "Meksyk",
    "Mołdawia", 
    "Monako",
    "Nepal", 
    "Niemcy",
    "Norwegia",
    "Nowa Zelandia",
    "Panama",
    "Peru",
    "Polska", 
    "Portoryko", 
    "Portugalia",
    "Rumunia",
    "Seszele",
    "Słowacja", 
    "Słowenia", 
    "Somalia", 
    "Sri Lanka", 
    "Stany Zjednoczone",
    "Szwajcaria", 
    "Szwecja",
    "Tajlandia",
    "Tunezja",
    "Turcja",
    "Wielka Brytania", 
    "Wietnam", 
    "Włochy",
    "Zimbabwe", 
    "Zjednoczone Emiraty Arabskie"
];

